[tools]
# AI CLI 
claude = "latest"
codex = "latest"
gemini = "latest"
crush = "latest"
"npm:@github/copilot" = "latest"
"npm:@larksuite/cli" = "latest"
"npm:ctx7" = "latest"

# 开发语言
go = "latest"
python = "3.13"
java = "temurin-21"
node = "22"
rust = "stable"

# full stack
"npm:@angular/cli" = "latest"

# package management
uv = "latest"
maven = "3"

[tasks.omz-up]
description = "Update oh my zsh and plugins"
run = "zsh -c -i \"omz update\""

[tasks.brew-up]
description = "Update brew software"
run = "brew update && brew upgrade"

[tasks.mise-up]
description = "Update mise management software like claude"
run = "mise outdated && mise up"

